name: dart_rest_example
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  json_serializable: ^4.1.3
  shelf: ^1.1.4
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  shelf_router_generator: ^1.0.0
  build_runner: ^2.0.4
  json_annotation: ^4.0.1
